import os
TOKEN = os.getenv("TOKEN") if os.getenv("TOKEN") else "YOUR DISCORD BOT TOKEN" 
CONNECTION_STRING = os.getenv("CONNECTION_STRING") if os.getenv("CONNECTION_STRING") else "YOUR DB CONNECTION STRING"
CONNECTION_STRING = os.getenv("CONNECTION_STRING") if os.getenv("CONNECTION_STRING") else "YOUR DB CONNECTION STRING"